apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l1o6o6n24-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l1o6o6n24-python 
  name: l1o6o6n24-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l1o6o6n24-python 
